### ISSUE TITLE
[BUG] can not open file with colorscales

### ISSUE THREAD

**Issue by ahasoftware** [nikolaydubina/calendarheatmap#16]
Well, I just followed the install instructions from the readme:
```bash
go install github.com/nikolaydubina/calendarheatmap@latest
```

and then:
```go
cat my_file.json | calendarheatmap > my_heatmap.png
```

to only receive a fatal error:
```2021/07/15 10:58:42 can not open file: open assets/colorscales/green-blue-9.csv: no such file or directory```

**Comment by nikolaydubina** [comment]
Thanks, let me have a look.

**Comment by nikolaydubina** [comment]
Yes, I can repro. Will fix shortly.

**Comment by nikolaydubina** [comment]
Okay, so the issue is versions. v2 is not set properly for this module. Please clone and build from source. I will update in this ticket once this is solved. Thanks for flagging this!

**Comment by nikolaydubina** [comment]
Can you try again for installing `@latest`? You should get `v1.5.0`.

If it does not work, can you run bellow to verify versions you can see?
```bash
$ go list -m -versions github.com/nikolaydubina/calendarheatmap
github.com/nikolaydubina/calendarheatmap v1.0.0 v1.1.0 v1.1.1 v1.2.0 v1.3.0 v1.4.0 v1.4.1 v1.5.0
```

I retracted v2 for this project for now to reduce maintenance burden. API changes were not breaking and AFAIK we don't have anyone relying on packages from this module anyways.

Cheers,

**Comment by nikolaydubina** [comment]
Reopen Issue if it remains.

**Comment by ahasoftware** [comment]
It now works as expected! :tada: Thank you fixing it so quickly :+1: 

```bash
[me@localhost]$ go list -m -versions github.com/nikolaydubina/calendarheatmap
github.com/nikolaydubina/calendarheatmap v1.0.0 v1.1.0 v1.1.1 v1.2.0 v1.3.0 v1.4.0 v1.4.1 v1.5.0
```
